export { ConwayGame, createConwayGame } from './ConwayGame'
export { CellMap } from './CellMap'
export { CellTiles } from './CellTiles'
export { encodePattern, decodePattern, loadPatterns } from './patterns'
export type { Pattern, ConwayOptions } from './types'
